### ISSUE TITLE
Make link to bc parks website accessible within park description in DUP

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#262]
Currently within DUP the park description has an autogenerated link to the relevant bc parks page (autogenerated when this field is populated in DUP-admin) - this link advises users to "click here" which is not accessible.

![Image](https://github.com/bcgov/parks-data-register/assets/38668130/1fea01aa-493d-4405-a169-8c29e9baac50)

This ticket is to change the text to read: For more information about abc Park, visit the BC parks page. 
And have BC Parks page be the hyperlink.

## Acceptance Criteria
- BC Parks page is hyperlinked to the page specified in DUP admin
- here. is removed from sentence
-

**Comment by manuji** [comment]
Tested on TEST: **Passed** ✅
* Verified that this change request has been implemented.

**Comment by JLWade** [comment]
looks good moving to done
