### ISSUE TITLE
DUP Public-> Display captcha error instead of a proper user message

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-reso-public#277]
Scenario:
* Navigate to the DUP Admin and select a park, Facility and set the passes required.
* For the field "Booking days ahead" field select: Same day only. 
* Save the changes and try to book a pass for the above selected park/facility for the next day.

Issue:
* Even though the passes can be booked on the same day, the user is given the option to select the next day and when proceeding to the page to enter details, the Captcha shows an error instead of explaining the actual issue there. 

Expected:
* Instead of showing the captcha error, either we should disable the next date on the calendar or let the user know that the passes can only be booked on the same day. 
  * disable next date on calendar so user cannot select a date that is not available 

![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/e3170ff8-7443-4431-abc8-bf88211a39c1)

![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/f7e20509-09ae-47fd-b5aa-40d3880b9d04)

**Comment by marklise** [comment]
I cannot repro this at 2024-01-18 2:19PM for a same-day configuration PM pass.

https://github.com/bcgov/parks-reso-public/assets/51633/6e0d1da8-fd1c-495d-8e50-f33a13598213

![image](https://github.com/bcgov/parks-reso-public/assets/51633/141a7563-a64a-4eb3-b6f7-e2eef4589c73)

**Comment by marklise** [comment]
@manuji I wonder if this occurs during the AM only?

**Comment by manuji** [comment]
@marklise , I just checked at 12:07 pm and I can recreate it in PM as well. Either way if we can get this bug fixed that would be great.

**Comment by Dianadec** [comment]
@manuji will share recording of start to finish and will add to the ticket for @marklise  to review.

**Comment by manuji** [comment]
Hi @marklise , here is the recording from the incognito window. 

https://github.com/bcgov/parks-reso-public/assets/65190263/7b2d256c-421f-47c4-9966-204c3996596c

**Comment by LindsayMacfarlane** [comment]
Hi @marklise @manuji - it looks like some work was already done on this ticket and I tried to recreate (without any luck). Can you please confirm if this is still an issue that needs fixing?

**Comment by manuji** [comment]
Hi @LindsayMacfarlane , I will assign this to myself and check again. Thank you.

**Comment by manuji** [comment]
Tested on TEST: Verified that this issue is no longer valid as the captcha has been removed from the workflow. Closing the ticket.
