### ISSUE TITLE
Convert contact form from using ngModel to Reactive Forms

### ISSUE THREAD

**Issue by Christopher-walsh22** [bcgov/parks-reso-public#306]
A console warning has been appearing in the contact form alerting that you should not use Reactive forms and ngModel on the same form. From looking at the code it is clear that all fields (except phone number) are using ngModel. Some research will be required to determine which of these fields is also using reactive forms. 

Acceptance Criteria:
[] Warning no longer appears in console when loading contact form. 

![Image](https://github.com/bcgov/parks-reso-public/assets/106549296/c1ca657e-4886-4335-a592-76ef790b1fc9)

**Comment by JLWade** [comment]
@Christopher-walsh22 is this something that should be done this spritn?

**Comment by Christopher-walsh22** [comment]
@JLWade  No I thought I deleted this ticket, It was resolved with the last release of SMS messages.
