### ISSUE TITLE
QR code missing in print confirmation page

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-reso-public#323]
## Describe the bug
When a user gets the confirmation of their DUP reservation on the DUP reservation site, they can get a QR code+reservation#, but if they wish to save this reservation information using 'print' button provided on the same page or in the email confirmation of their reservation, only reservation# appears and the QR code is missing. This is leading to user writing emails to parkinfo as well as causing confusion to the public about the relevancy of multiple confirmation codes provided.

### To Reproduce
1. Go to [DUP Test environment](https://d2yc82svj0l8d5.cloudfront.net/dayuse/)
2. Scroll down to `Select a Park`
3. Click on `Book a Pass` under any park name that requires a DUP
4. Scroll down and select a `Visit Date` and a `Pass Type`
5. Enter `Number of Passes Required` if applicable
6. Hit `Next`
7. Give information in the required fields: `First Name`, `Last Name`, `Email Address`, `Please Re-Type Your Email Address`; check the `I have read and agree to the above notice` box; and enter the Captcha Code
8. Hit `Submit`
9. You will see your information (similar to that in Attachment A below) i.e. apart from other information, it will have a QR code **and** a Reservation#
10. Hit `Print`
11. A new browser tab will open up (similar to Attachment B below) where you will see the same information from previous page, **except** the QR code is missing

### Expected behavior
If the QR code is turned on for a facility, then it is included in the printable page of the users reservation.

## Screenshots
- Attachment A: This pdf shows the print version of the page that a user will see when they get a reservation confirmation [BC Parks - Day Use Pass.pdf](https://github.com/bcgov/parks-reso-public/files/14621493/BC.Parks.-.Day.Use.Pass.pdf)
- Attachment B: This pdf is the document that opens up in a new browser tab after the user clicks on 'print' button on the previous page: [download.pdf](https://github.com/bcgov/parks-reso-public/files/14621494/download.pdf)

### Desktop (please complete the following information):
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 122.0.2365.80 (Official build) (64-bit)

**Comment by JLWade** [comment]
@kgorana can you add steps on how to reproduce this bug and what environment you are seeing it in? 
You can also use your new scrum master skills and add some acceptance criteria if you like!

**Comment by davidclaveau** [comment]
@manuji should be good to review in DEV now!

It's pretty tricky to replicate, but I found that opening dev tools, navigating to Network, and changing the speed from "No throttling" to "Slow 3G" was the most consistent way to find the bug.

![Image](https://github.com/bcgov/parks-reso-public/assets/62899351/82de7d0e-b328-464d-b7c8-7b8f09529b2c)

You should now see that the print screen that pops up is a little slower after clicking the "Print" button, as it now waits for the QR image to load fully into the pop-up box.

Let me know if anything is amiss!

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed. Thank you @davidclaveau , working for me even with offline. 
* Ready for PO review.

**Comment by JLWade** [comment]
@kgorana thanks for PO reviewing this one - moving to done
