### ISSUE TITLE
[M] Public - Update Back Button

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#333]
#### Description:

Need to change the button that currently shows as '<- Facilities' in the Contact info page, and '<- Home' on the Parks page to a button that says 'Back', moved to the bottom-right.

#### Acceptance Criteria:
[Note: Use 'Given/When/Then' format if it makes sense to. Otherwise, a simple checklist that can be tested.]

- [ ] Contact Information Page: Current "Facilities" text is removed and a blue button labeled Back replaces it.
- [ ] Button moved to bottom right of the page.
- [ ] Back button navigates you back to the parks select a pass type page
- [ ] Clicking back button produces a warning for navigating away from this page (see ticket #334)
- [ ] Park Page: Current "Home" text button is renamed to "back" and moved to the bottom right.

Figma link: https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=3975%3A17140&mode=design&t=YbmeWNjWNn9tCaMc-1

https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=3980%3A18613&mode=design&t=YbmeWNjWNn9tCaMc-1

#### Development Checklist:

- [ ] Any UT's are updated.

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Update: Move button to the bottom - evenly spaced - see wireframe: https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=3980%3A18613&mode=design&t=rRuWQGWHaOC5p2HU-1

**Comment by Dianadec** [comment]
@danieltruong fyi I have added the Parks page "home" button to be renamed to "Back" and also moved to the bottom right for consistency. CC @JLWade @ndelraye . See teams post for context: https://teams.microsoft.com/l/message/19:7gg3pxzoL-hjZRHvr5ggkjxP9O8cah6SWqiYiz2CD_M1@thread.tacv2/1712858476567?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=aadf267c-d6ab-4c8c-9cff-e574713575e6&parentMessageId=1712691088221&teamName=External%3A%20Team%20Osprey&channelName=General&createdTime=1712858476567

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the UI has been updated as per the requirement. 
* Passing to PO review.

**Comment by JLWade** [comment]
working as expected moving to done
