### ISSUE TITLE
Update content on Park booking page

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#339]
#### Description:

As a potential park visitor, I want to easily view and understand info on the booking page of DUP so that I can book a pass. 

This ticket is to update text and content on park booking page to align with best web content practices and plain language. Please note many updates are capitalizations and hyperlink updates. 

Updates found here:
https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7BA34EA26A-4F09-4BAC-B27C-4D3018643484%7D&file=day-use-pass-system-mount-seymour-v0.1.docx&wdLOR=cB7A430E5-82D6-44AF-BC63-A2A1501CD792&action=default&mobileredirect=true

Current view:

![Image](https://github.com/bcgov/parks-reso-public/assets/38668130/815200a0-a037-46fa-a32c-e4b4adf9db0e)

Figma link: https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=4441%3A9725&mode=design&t=St5SW8v1cpTULiyZ-1

#### Acceptance Criteria:
_updated content found in link above_

On the park booking page...

- [x] 1. ~~content is updated in the yellow important booking info box~~. Copy matches what was changed in #338 from [this document here](https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7B008EAE24-83BE-4F84-B144-F77470B79C29%7D&file=day-use-pass-system-home-v0.1.docx&wdLOR=c1A82600D-B28E-4F56-B44A-A7BBBAD44E48&action=default&mobileredirect=true)
- [x] 2. content is updated in the trail info box that pops up.
- [x] 3. content is updated in the grey guidelines box.

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by JLWade** [comment]
ticket in blocked to save for when David is ready to pick up for onboarding

**Comment by ndelraye** [comment]
Marshall has approved attached updates, this ticket is ready to go

**Comment by davidclaveau** [comment]
Should be ready for QA review!

**Comment by davidclaveau** [comment]
Should be good to review!

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the copy updates requested in the 3 locations of the individual park pages have been done. 
* There are minor differences between the Figma designs and the implementation, but not a blocker for the PROD deployment. 
* Passing to PO review for approval to deploy to PROD.  @JLWade

**Comment by JLWade** [comment]
Thanks for the flag Manuji - I think we can leave as is and update figma when we can. 
Moving to done
