### ISSUE TITLE
[S] Update content on contact booking page

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#340]
#### Description:

As a park visitor, I want to easily view and understand the contact information booking page so that I can book a day use pass. 

These content/text updates are to align with best practices, web standards, and plain language. Many changes are capitalizations and hyperlinks.

Updates can be found here:
https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7BC0BFF40A-5D36-48AA-9FC1-CC53D09E3593%7D&file=day-use-pass-system-contact-info-v0.1.docx&wdLOR=cD80D004D-8BCE-4337-835F-AD75E0DE01EC&action=default&mobileredirect=true

Current view:
![Image](https://github.com/bcgov/parks-reso-public/assets/38668130/326becb4-84c1-4b26-bc51-61d8836fcfae)

#### Acceptance Criteria:
_updates mentioned below are reference in doc above_

On contact entry page...

- [x] 1. content updates are made to sentence under contact information title
- [x] 2. content updates are made to # of parking passes text in blue box
- [x] 3. content updates are made to data entry form, including to disclaimers and privacy notices

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [x] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [x] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [x] Work is traceable in GitHub
  - [x] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by davidclaveau** [comment]
Should be good to review on dev now!

**Comment by manuji** [comment]
@davidclaveau , looks like the code for this also missing.

**Comment by manuji** [comment]
Tested on TEST: Pending
* Few copy errors found as below;
1. Missing a comma 
![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/dbf74886-7815-4903-9bc3-905c1f494c33)

2. Duplicate periods after the postal code. 
![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/8ab157af-1846-413d-b676-3f54ddb31b42)

FYI @davidclaveau

**Comment by davidclaveau** [comment]
@manuji fixed typos and should be ready for review in dev!

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed and the task has been completed. 
* Ready for PO review on TEST environment.

**Comment by JLWade** [comment]
caught one small thing which is probably not a big deal but since we're already making these updates I thought I'd mention it - the Number of Trail Passes, should remove T for t and P for p to get rid of those capitals. This will only happen on trail passes (joffre right now)


![Image](https://github.com/bcgov/parks-reso-public/assets/38668130/1dc79ec7-7f75-4a1b-8d28-00cc0b1c5d6b)

@manuji @davidclaveau  will move to inprogress to update

**Comment by davidclaveau** [comment]
@manuji updated the text @JLWade highlighted - should be in DEV now 😄

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the changes requested by Jess have been made.
* Ready for PO review.

**Comment by JLWade** [comment]
looks good moving to done.
