### ISSUE TITLE
[S] Update content on success page

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#341]
#### Description:

[User Story]

[Description of the ticket]

Updates required here:
https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7B4ED28D03-2139-4A4E-8987-293F5EC2EF18%7D&file=day-use-pass-system-success-v0.1.docx&wdLOR=c968C8893-A4CA-4CA4-89F5-6127C1F50CDA&action=default&mobileredirect=true

Current view:

![Image](https://github.com/bcgov/parks-reso-public/assets/38668130/4961fb41-d44d-48ab-9106-3e57b6f8bb0d)

#### Acceptance Criteria:
_updates mentioned below are in link above_

On the success pass page...

- [x] 1. content is updated to the success info on left hand side
- [x] 2. content is updated to next steps section 

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [x] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [x] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [x] Work is traceable in GitHub
  - [x] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by davidclaveau** [comment]
In dev and ready for review!

**Comment by manuji** [comment]
@davidclaveau, none of the changes are reflected on Dev or TEST. Could you please check if you have merged the code for this ticket? Thank you.

**Comment by manuji** [comment]
Tested on TEST: Pending
* Two issues were seen with the copy under the section "Next steps". One is instead of the word "by", the word "via" has been used and the second is missing a comma. Please refer to the attached screenshot for further details. 


![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/b1f5c1b0-a0ee-41f1-8df1-24f3f5ef23b4)

FYI @davidclaveau

**Comment by davidclaveau** [comment]
@manuji the fixes are in dev for review now!

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the issues have been fixed and the task has been completed. 
* Ready for PO review. @JLWade

**Comment by JLWade** [comment]
looks good moving to done
