### ISSUE TITLE
[S] Update content on cancel pass page

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#342]
#### Description:
As a park visitor, I want to know how to cancel my pass so that I can cancel it. 

This ticket is to update content on the cancel pass page. It includes updates for best practices, web standards, and plain language. Many updates are capitalizations or hyperlinks. 

Updated content can be found here:
https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7BB2E04E68-9C73-45AC-A16D-0FEB62417846%7D&file=day-use-pass-system-pass-lookup-v0.1.docx&wdLOR=cD4BA6755-8B99-4DBC-8D8B-0A3994F5C20E&action=default&mobileredirect=true

Current view of cancel page (must be clicked by user from their email)

![Image](https://github.com/bcgov/parks-reso-public/assets/38668130/6132aa78-343f-4eef-a687-5bf35754efad)

#### Acceptance Criteria:
_content updates mentioned below are in link above_

On cancel a reservation page (that is clicked from users DUP confirmation email)...

- [x] 1. content is updates on cancel a reservation page

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [x] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [x] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [x] Work is traceable in GitHub
  - [x] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by davidclaveau** [comment]
Ready for review in dev!

**Comment by manuji** [comment]
Tested on TEST: Pending
* There are two issues with the copy, one is placing the period after the single quotation mark in sentence: **'Yes, this is my reservation information'.** Second one is missing the last sentence: "Thank you for cancelling and making your pass available to other visitors."

Implementation is below:


![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/9fa33cdb-f644-4e7b-b6a8-3efb54ef6622)

Required copy:


![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/b6d7ab46-d4b0-4774-831c-c2b5b138c32a)

Moving this back to Todo. FYI @davidclaveau

**Comment by davidclaveau** [comment]
@JLWade I think I need your opinion on how the content changes are showing and if the logic all makes sense!

In the document, it shows as making a few changes to the page, one of which is adding "Thank you for cancelling and making your pass available to other visitors". I assumed this was to be added _after_ the user had cancelled - replacing what was there previously, which was "Your reservation has been cancelled" which popped up after final cancel confirmation.

Just wondering if that all makes sense! I assumed it made more sense to thank the user after they cancelled, but I could be convinced otherwise!

![Image](https://github.com/bcgov/parks-reso-public/assets/62899351/ad97a745-5056-4815-8721-2289d1cac0b6)

**Comment by JLWade** [comment]
Good catch @davidclaveau  - I think you're right, let's have that line after the confirmation. Can you update the teams word doc too?

**Comment by davidclaveau** [comment]
@manuji fixed that typo - should be good to review in DEV!

That "Thank you for cancelling and making your pass available to other visitors." section will only show when the user cancels their pass.

Let me know if anything is amiss!

**Comment by manuji** [comment]
Thanks @davidclaveau . 

Tested on TEST: **Passed**
* Verified that this task has been completed. 
* Passing to PO review.

**Comment by JLWade** [comment]
nice team work! moving to done
