### ISSUE TITLE
Designs: Facility-specific confirmation email ->Joffre

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#344]
#### Description:

This ticket is to create any relevant designs for facility specific messaging on DUP confirmation emails. 

#### Acceptance Criteria:

- [ ] Confirmation email designs for facility specific messaging are in figma and linked [here](https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=4789-1888&t=DfCaMrcNVjCTrR3f-1)
- [ ] Each parks messaging will be unique to the facility and include the same information and links as the parks success page
- [ ] Current messaging - Your feedback is incredibly valuable and influences how we shape our online information, if you would like to provide feedback about your experience using our booking system please send an email with your thoughts to [BCParksUserResearch@gov.bc.ca](mailto:BCParksUserResearch@gov.bc.ca). - is deleted from all emails
- [ ] Email message for Joffre is as follows:

Day Use Pass – ALL DAY/AM or PM
Joffre Lakes Park – BC
Joffre Lakes
3 trail pass(es)
Date

Nice people make nature nicer – share the park by complying with pass times. Please ensure you arrive and depart according to the times on the pass you have booked.

If you can no longer make the trip, please cancel your reservations and allow the passes to be re-allocated to other park visitors. Cancel your pass.

Reservation Number: # Name

Please ensure you have your pass available to show BC Parks staff when required; print or save/screenshot a copy of this email and the QR code to your phone as proof of your booking, as Wi-Fi connectivity is not always reliable within the parks.

If you have booked more than 1 trail pass on your reservation please ensure all members of your party are in attendance when checking in, you must all be checked in at once using the same pass.

**Visitor Guidelines**
(this section will use the vertical grey bar as bullets are not possible in GCNotify)

Always use designated parking lots, walkways, and facilities.  
Be prepared. Learn how to call [ AdventureSmart’s 3Ts](https://www.adventuresmart.ca/the-three-ts/). 
Check the[ park page](https://bcparks.ca/joffre-lakes-park/ ) for advisories.
[Respect wildlife](https://bcparks.ca/plan-your-trip/visit-responsibly/wildlife-safety/). Keep your distance and don’t feed wildlife, including birds!  
Respect other park users. Do not play music out loud.  
There are no garbage cans along the trail. Understand your responsibility to[ #LeaveNoTrace](https://www.youtube.com/watch?v=Qm3U9eKha74&ab_channel=CallingMountainsProductions) by packing out anything you pack in.  
Pets are not permitted in Joffre Lake Parks.

Thank you and we hope you enjoy your visit!

#### Dependencies
- Blocked by #343 
- Blocking #397 

**Relevant documentation as reference**
- teams chat with more info: https://teams.microsoft.com/l/message/19:07e0829d25914edc840a9e0f6015ffd3@thread.tacv2/1713300125334?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=cb2c4bec-527d-4097-80b2-6e40e98d36bf&parentMessageId=1713300125334&teamName=Parks%20%26%20Recreation%20Transformation%20(Open%20X-Gov)&channelName=%5BProduct%5D%20Day%20Use%20Pass&createdTime=1713300125334

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Refinement notes: 

Want to be able to provide facility-specific confirmation messaging after someone books a facility. they would see specific information in their email that shares info/heads-up info about where they are going. eg: safety, make sure you know before you go, etc.
Content is being drafted.
Aim is to iron this out prior to the following sprint for implementation.
Depends on capacity of Nicole since we are doing a lot for backcountry etc.

**Comment by JLWade** [comment]
Notes from refinement May 28, 2024:
- should this be split into two design tickets: success confirmation page and email confirmation (@meyerdarcie will split into 2)
  - info/text will be the same but two separate locations for updates
- @MarshallHenson is working on content that can be added to designs

**Comment by MarshallHenson** [comment]
content is located [here ](https://bcgov.sharepoint.com/:w:/r/teams/031072/Shared%20Documents/%5BProduct%5D%20Parking%20Services/DUP%20Reso%20Site%20Content/Responsible%20Rec%20Messaging/DUP%20RR%20messaging%20DRAFT.docx?d=wf8072de934fb4795810ecb70ec3983a4&csf=1&web=1&e=CCDi0u)

**Comment by Dianadec** [comment]
Refinement notes:
- we'll break out these tickets (design/implementation) further async this week - and Darcie to meet with Nicole/Marshall to clarify some details. Eg: split tickets by park.

**Comment by meyerdarcie** [comment]
@MarshallHenson to re-draft content for the email templates in word doc:
 https://bcgov.sharepoint.com/:w:/r/teams/031072/Shared%20Documents/%5BProduct%5D%20Parking%20Services/DUP%20Reso%20Site%20Content/Day%20Use%20Pass%20Confirmation%202022%20Email%20Update.docx?d=w04e16b37aa0247f19ee6970ed3a9d29b&csf=1&web=1&e=TkMQf7

FYI @ndelraye
