### ISSUE TITLE
Update BC Parks Logo Link

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#347]
#### Description:

The current logo at the top-left of the page leads to the main bcparks.ca website. We want it instead to link to reserve.bcparks.ca/dayuse/

#### Acceptance Criteria:

- [ ] BC Parks logo links to https://reserve.bcparks.ca/dayuse/ in a new tab

![Image](https://github.com/bcgov/parks-reso-public/assets/35785153/19dd3d13-4421-4f35-be1b-988efd1e636c)

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by jpeersoxd** [comment]
Verified on TEST. No issues found. Moving to PO Review.

**Comment by JLWade** [comment]
linking to DUP - moving to done
