### ISSUE TITLE
Step 1: Theme Aug 2023 Emails

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#350]
# Description:

Analyze all 600 emails sent to parkinfo for Aug 2023 that are relevant to user feedback (ie. not from staff) by theming them into categories. These themes/categories can be used as user research to inform the DUP team about what inquires, complaints and feedback are coming in via this avenue (parkinfo inbox).

## Acceptance Criteria:

- [x] Emails from Aug 2023 (600) have been reviewed and each one has been themed/categorized based on content (please see dev check list for scope)
  - [x] when not possible to categorize, email can be skipped 
- [x]  determine percentage of overall emails that fall under each category
- [x] list of categories and percentage of emails is provided
  - [x] just theme/category title and % number (report with more detail is in another ticket)
- [x] Identify park mentioned in email if possible (assist with one of the charts) 

## Development Checklist:

- Read through emails Max 2 times
- Maximum of 16 categories/themes identified
  - Sub categories are not necessary

### Dependencies
- access to emails

### Definition of Ready

- [x] Acceptance criteria are included
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Ticket has been refined in collaboration with PO and questions answered

### Definition of Done
- In progress:
  - [x] Acceptance criteria are complete
- PO Review:
  - [ ] Acceptance criteria are confirmed complete
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- see #354 for charts needed
-

**Comment by kgorana** [comment]
**At least** 40 emails each day to finish theming in 15 days (i.e. 3 workweeks):

- [ ] Monday, April 15 - Index# 260-300
- [ ] Tuesday, April 16 - Index# 301-340
- [ ] Wednesday, April 17 - Index# 341-380
- [ ] Thursday, April 18 - Index# 381-420
- [ ] Friday, April 19 - Index# 421-460
- [ ] Monday, April 22 - Index# 461-500
- [ ] Tuesday, April 23 - Index# 500-540
- [ ] Wednesday, April 24 - Index# 541-580
- [ ] Thursday, April 25 - Index# 581-620
- [ ] Friday, April 26 - Index# 621-660
- [ ] Monday, April 29 - Index# 661-700
- [ ] Tuesday, April 30 - Index# 701-740
- [ ] Wednesday, May 1 - Index# 741-780
- [ ] Thursday, May 2 - Index# 781-820
- [ ] Friday, May 3 - Index# 821-860
- [ ] Monday, May 6 - Index# 861-670
- [ ] Tuesday, May 7 - Buffer Time

**Comment by kgorana** [comment]
Just posting an update:
As of 05/07/2024, all emails from Aug 2023 (611) were reviewed and each one had been themed/categorized based on content.
On 05/08/2024, now moving on to finding % of emails in each of those categories.

**Comment by JLWade** [comment]
Moving back to inprogress to incorporate category name suggestions/updates and adding the correct percentages.

**Comment by JLWade** [comment]
updated list looks good - moving to done
