### ISSUE TITLE
Step 3: Draft Take-Aways for each Theme

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#352]
#### Description:

While analyzing and reviewing the 600 Aug 2023 emails, start to identify some key take-aways for each theme that is identified.

#### Acceptance Criteria:

- [x] Identify and write down 1-5 take-aways for each theme that is being identified in #350 

#### Development Checklist:

- Read through emails Max 2 times
- Maximum of 16 categories/themes identified
  - Sub categories are not necessary
- Maximum 1-5 take-aways for each theme/category
  - If there are more, prioritize the most valuable 1-5

**Dependencies**
- access to emails

**Definition of Ready**

- [x] Acceptance criteria are included
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been reviewed and questions answered

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are complete
- PO Review:
  - [ ] Acceptance criteria are confirmed complete
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by kgorana** [comment]
- [ ] [Plain Language Checklist and Resources](https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/policies-procedures-standards/web-content-development-guides/plain-language-course/plain_language_checklist.pdf)

**Comment by JLWade** [comment]
moving to done
