### ISSUE TITLE
DUP- Update the text inside "Important booking information" to include the pass hold time information

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-reso-public#364]
After implementing the pass hold feature, we need to update the copy inside the "Important booking information" to include the line about the pass hold time as given in the word document [here](https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7B008EAE24-83BE-4F84-B144-F77470B79C29%7D&file=day-use-pass-system-home-v0.1.docx&wdLOR=c1A82600D-B28E-4F56-B44A-A7BBBAD44E48&action=default&mobileredirect=true).

![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/6f9456d1-3572-46c6-b08b-55db2a3c9016)

- [x] line is added to show text above but 7mins

**Comment by JLWade** [comment]
blocked until hold feature is in prod and done and this becomes valid

**Comment by Dianadec** [comment]
Will decide on the time limit amount and update accordingly.

**Comment by JLWade** [comment]
Updated ticket to 15mins

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this task has been completed. 
* Passing to PO review.

**Comment by meyerdarcie** [comment]
Working as expected, moving to done - do not deploy this to production until hold pass feature is ready to go.
