### ISSUE TITLE
Remove "safety" from park video button

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#388]
#### Description:

This ticket is to remove the word "safety" from the park video button on the day use pass booking page.

![Image](https://github.com/bcgov/parks-reso-public/assets/38668130/7e276166-912d-42b9-81f7-216865cca1ee)

#### Acceptance Criteria:

Given I am a day use visitor 
When I click on a specific park to book a day use pass at
Then I see an option to view a park video to prepare for my trip

- [x] the word "safety" is removed from video button

#### Development Checklist:

- [ ] 
- [ ] ...
- [ ] ...

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this task has been completed.

**Comment by meyerdarcie** [comment]
Looks good - moving to done.
