### ISSUE TITLE
Increase width of text on FAQ page for DUP

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-public#389]
#### Description:

This task is to increase the width of the text on the DUP FAQ page. 

#### Acceptance Criteria:
Given that I'm a day use pass visitor 
When I'm on the FAQ page
Then I want to see the text fill the page 

- [x] Increase the width of the text on the FAQ page (use homepage template)
- [x] Verify the spacing is working on mobile on desktop 

![Image](https://github.com/bcgov/parks-data-register/assets/169185865/76bbbd2d-064e-4084-a048-a329a1fa9f8d)

#### Development Checklist:

- [ ] Use homepage template
- [ ] ...
- [ ] ...

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by manuji** [comment]
Tested on TEST: **Pending**
* Verified that the width the text would flow has been increased.
* After this change the option to navigate to the home has UI issues with the alignment. The arrow is no longer aligned with the "Home" word. 
* Also, the space between the page heading "Frequently Asked Questions" and the content reduced.
* I am noticing font color of the heading has changed as well, I would consult @janemoxd or @meredithom for the correct font colors. (As per my general knowledge H1 font should be in color code "#036")


![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/2e53dc1e-9fe3-496a-99db-6e000396e324)

**Comment by meredithom** [comment]
After looking into this, I've noticed the button is misaligned on the Cancel a Pass page as well so I believe it is unrelated to this ticket:
![image](https://github.com/bcgov/parks-reso-public/assets/15185966/d219bebc-9d76-4493-909d-b7441aae6211)

I'm looking into the spacing now but I'm only seeing the problem when bullet points are involved.. with standard text it looks as I would expect. 

Heading text colour should be coming from the bootstrap library, which was updated recently.

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this task has been completed and the issues mentioned in my previous comment have been fixed. 
* Passing to PO review.

**Comment by meyerdarcie** [comment]
Working as intended, moving to done.
