### ISSUE TITLE
[S] Update Error message in DUP when passes are sold out

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#395]
#### Description:

The error toast is confusing users thinking it is a system error but really it is just that the passes are sold out. This task is ONLY to update the messaging. In future, we will consider the redesign of DUP front-end and how it will be integrated with PRDT. The toast will be updated to a Modal.

#### Acceptance Criteria:

Given that I am a potential park visitor
When I click to reserve a DUP at the same time as someone else and there are no more passes available
then I see a "Sold out" message as per this figma link wording, but as a modal (see dev checklist):

Modal title: (no title - just use wording in the message)
Description:
"Sorry, all passes for this time and date have been reserved. Please make a new selection or try again later."

Library link: https://www.figma.com/design/3Zthj9Ci5QoJOAz6p3TcLP/BC-Parks---Admin-Library?node-id=326-68874

 Figma link https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=4074%3A6376&mode=design&t=YbmeWNjWNn9tCaMc-1

#### Development Checklist:

- [ ] Use bootstrap modal component?
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
-this is the current message we see: ![Image](https://github.com/bcgov/parks-reso-public/assets/35785153/43c335fa-fd9e-480e-a830-86f3c14d6206)
-

**Comment by Dianadec** [comment]
standup Notes: 
- for now this will resolve the issue
- but in future, this page could be redesigned to show the remaining capacity (high-med-low)
- this will be relevant to backcountry as well

**Comment by Dianadec** [comment]
Refinement notes:
- separate but related issue is the multi-toast messages
- Language to be updated: "Sorry, all passes for this time and date have been reserved. Please make a new selection or try again later. "

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the duplicate error messaging has been replaced with one proper error message with the copy given on the figma. 
* Refer to the error message on desktop and mobile below. 


![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/036f28ab-8e7d-4e7c-9d72-d9f9ab71f445)



![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/dce8d8bf-e32d-4264-9ecc-addd0c01643a)

**Comment by meyerdarcie** [comment]
Looks good - moving to done.
