### ISSUE TITLE
[M] DUP Facility specific messaging added to GARIBALDI DUP confirmation pages

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-public#401]
#### Description:
As a Garibaldi visitor, I want to get park specific information so that I can be better prepared. 

As a bc parks staff, I want to provide park specific information after a user has booked a day use pass so they can be better prepared. This is part of responsible recreation messaging. 

#### Acceptance Criteria:

- [ ] Update Garibaldi confirmation pages with approved text and links as per the design ticket: https://github.com/bcgov/parks-reso-public/issues/399
- [ ] 

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by #399 
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Confirming with Nicole whether we need to wait for the icons to be decided for the new bullets.
https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=5046-2432&t=OasmEf9QLpmr4REv-1

@meyerdarcie  @ndelraye

**Comment by ndelraye** [comment]
Yes, this ticket is blocked until we get decisions on the new icons, will try to get them today

**Comment by Dianadec** [comment]
Icons have now been added. See design ticket

**Comment by manuji** [comment]
Tested on TEST:

* Need more space between the Safety information section and the Visitor guidelines heading.

**Comment by Christopher-walsh22** [comment]
@manuji just wanted to leave some screenshots of the fixes Im putting in for this. Let me know if I am missing anything :) 


Print button moved to above safety information when mobile:

![Image](https://github.com/user-attachments/assets/697ebde8-8027-408a-88d7-2069bd3ca3ce)



Diamond Head Spacing and alignment:


![Image](https://github.com/user-attachments/assets/823d7a0d-2e8b-4442-a3e7-c632bc439db5)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* verified that this task has been completed and the issues have been fixed. 
* Passing to PO review before PROD deployment.

**Comment by meyerdarcie** [comment]
Looks good and working as intended, moving to done.
