### ISSUE TITLE
Issue with links in the RichHTML box on park pages

### ISSUE THREAD

**Issue by MarshallHenson** [bcgov/parks-reso-public#405]
**Describe the bug**
Hyperlinks in the RichHTML do not open in a new tab, meaning users could be taken away from the booking page when interacting with the content (and thus potentially losing out on an opportunity to book a pass). 

**To Reproduce**
1. Go to ['reservation site'](https://reserve.bcparks.ca/dayuse/registration) 
2. Click on any of the links that are created via the RichHTML box 
3. See error

**Expected behavior**
Any links on the DUP page should default to opening in a new tab. 

**Screenshots**

![Image](https://github.com/bcgov/parks-data-register/assets/150951308/f28ed76d-564c-447e-aba4-94bee87177b3)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Chrome 
 - Version 125.0.6422.141/142 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 
 - OS: iOS 17.5.1
 - Browser Chrome 
 - Version: 126.0.6478.54

**Comment by MarshallHenson** [comment]
medium priority. i can't imagine it is a big ticket so whenever it works to pull in

**Comment by Dianadec** [comment]
Standup notes: Enable users to do links using the wysiwyg rather than copying and pasting from word.

**Comment by manuji** [comment]
Testing blocked by https://github.com/bcgov/parks-reso-public/issues/459

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this feature has been implemented. 
* Verified that the richtext editor now has an option to add links and settings to set the link to open in the same window or new window. 
* Passing to PO review. 

![Image](https://github.com/user-attachments/assets/b8167459-d1b1-48f3-b8e4-c360f3b4e510)

**Comment by LindsayMacfarlane** [comment]
Tested in test via Mount Seymour by adding in a link and having it open in the same window. Passed and approved. 

Thank you @Christopher-walsh22 for helping me troubleshoot and for all your testing @manuji !
