### ISSUE TITLE
Review FontAwesome License Policies

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#416]
#### Description:

In order for us to move forward with a FontAwesome paid license, we need to first look into the policies associated with it to avoid any negative effects down the road.

Next steps of procuring the license include:
1. Mark to review the license policies to make sure what we are choosing is all good 2. Decide on which subscription. and 3. Determine how to pay. 

See teams threads for context:

https://teams.microsoft.com/l/message/19:7gg3pxzoL-hjZRHvr5ggkjxP9O8cah6SWqiYiz2CD_M1@thread.tacv2/1718999637844?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=aadf267c-d6ab-4c8c-9cff-e574713575e6&parentMessageId=1718999637844&teamName=External%3A%20Team%20Osprey&channelName=General&createdTime=1718999637844

https://teams.microsoft.com/l/message/19:641107af14164e7dae72f4d2cec75311@thread.tacv2/1719601934563?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=aadf267c-d6ab-4c8c-9cff-e574713575e6&parentMessageId=1719601934563&teamName=External%3A%20Team%20Osprey&channelName=Design%20Chat&createdTime=1719601934563

#### Acceptance Criteria:
[Note: Use 'Given/When/Then' format if it makes sense to. Otherwise, a simple checklist that can be tested.]

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
After this ticket has been completed let's setup another discussion with the other team.

**Comment by marklise** [comment]
**You’ll want to count a seat for these folks.**
- Designers placing icons in their digital and graphic designs
- Developers directly referencing icons in their source code
- Writers, bloggers, and content creators who use icons directly in their pieces

Plan to purchase: Pro Max based on the number of seats we need.

Self-hosting does not change anything as is irrelevant. OXD cannot give us ability to use the license without adding seats to cover each individual. Business should purchase the plan and assign everyone who falls into the category above.

**Comment by Dianadec** [comment]
Thanks for the info Mark - I'll be working with Darcie and the bc parks org to get the license payment sorted out asap. @marklise  @meyerdarcie
