### ISSUE TITLE
DUP: User able to book pass by changing system time to 6:50am

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-public#418]
**Describe the bug**
User reporting to ParkInfo that if system time is changes on laptop by 10 minutes, they are able to book passes early - the user changed system time to 6:50 from 7:00am and was able to book. 

**To Reproduce**
1. At 7:00am go to https://reserve.bcparks.ca/dayuse/
2. Change system time to 6:50am 
3. Reserve day use pass

**Expected behavior**
Despite system time, user is not able to book a pass until after 7:00am PST 

**Screenshots**

![Image](https://github.com/bcgov/parks-reso-public/assets/169185865/123b0fd9-a291-4449-b615-f0f64b05b13f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dianadec** [comment]
@manuji  did you get a chance to check out this bug? teams post reference: https://teams.microsoft.com/l/message/19:163facd69a2e4fe1a14eac3ae95fb3c4@thread.tacv2/1720635268881?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=aadf267c-d6ab-4c8c-9cff-e574713575e6&parentMessageId=1720632611866&teamName=External%3A%20Team%20Osprey&channelName=Dev%20Chat&createdTime=1720635268881

**Comment by manuji** [comment]
I will check it this morning @Dianadec , thanks for the reminder.

**Comment by manuji** [comment]
Confirmed that this is an invalid bug. Users cannot book passes just by setting the computer time as described by the user. Users cannot get past to the user information form and complete the booking. 

But, if the user sets their computer time as described, then they have the option to select the date in advance and select the facility bit early so they have less steps to do when the booking window is actually open giving them a head start.

**Comment by meyerdarcie** [comment]
Closing issue as per discussion on Jul 12.
