### ISSUE TITLE
DUP: minor home page text edits [XS]

### ISSUE THREAD

**Issue by MarshallHenson** [bcgov/parks-reso-public#419]
#### Description:

Small text change to https://reserve.bcparks.ca/dayuse/ as described [in this document.](https://bcgov.sharepoint.com/:w:/r/teams/031072/Shared%20Documents/%5BProduct%5D%20Parking%20Services/DUP%20Reso%20Site%20Content/Copy%20drafts/1.%20day-use-pass-system-home-v1.0-APPROVED.docx?d=w008eae2483be4f84b144f77470b79c29&csf=1&web=1&e=i4213A )
![Image](https://github.com/user-attachments/assets/d6f452fc-6e02-4d1d-9b59-d71f02ad084d)

#### Acceptance Criteria:

- [ ] Text on https://reserve.bcparks.ca/dayuse/ matches that in the word document. 
- [ ] Hyperlink to "https://bcparks.ca/reservations/day-use-passes/" is included in the text

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by meyerdarcie** [comment]
@MarshallHenson can you link the doc again? It's sending me to a 404 error.

**Comment by MarshallHenson** [comment]
https://bcgov.sharepoint.com/:w:/r/teams/031072/Shared%20Documents/%5BProduct%5D%20Parking%20Services/DUP%20Reso%20Site%20Content/Copy%20drafts/1.%20day-use-pass-system-home-v1.0-APPROVED.docx?d=w008eae2483be4f84b144f77470b79c29&csf=1&web=1&e=AldLw1

**Comment by manuji** [comment]
Tested on https://test-dup.bcparks.ca/dayuse/: **Passed**
* Verified that this change request has been implemented. 
* Passing to PO review.

**Comment by JLWade** [comment]
looks good in test - moving to done
