### ISSUE TITLE
[M] DUP Facility-specific messaging in GARIBALDI - EMAILS

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#420]
#### Description:

We need to create facility specific messaging in confirmation emails for GARIBALDI DUP bookings via GC Notify. 

#### Acceptance Criteria:
- [ ] Create new template for vehicle passes in Garibaldi as below
- [ ] Confirmation emails for vehicle passes will all use the same template, for Garibaldi this will be used for Rubble Creek, Cheakamus and Diamondhead
- [ ] Figma example: https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=5154-3532&t=HuJVGk7uHzK26w9h-1

Vehicle Pass text Template: https://bcgov.sharepoint.com/:w:/r/teams/031072/Shared%20Documents/%5BProduct%5D%20Parking%20Services/DUP%20Reso%20Site%20Content/DUP%20Vehicle%20Email%20Template.docx?d=w8bedc27c325340c3ad478c9fbd5ccafb&csf=1&web=1&e=XxUx53 

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Christopher-walsh22** [comment]
I have had a few conversations with @ndelraye about this ticket, and the best way to go about implementing it. In the end it sounds like the best path forward is to just update the existing template in GCnotify with the new information provided. 

Following the acceptance criteria: Garibaldi this will be used for Rubble Creek, Cheakamus and Diamondhead
And the decision from @MarshallHenson:  "They (Parking confirmation emails) also have to be applicable to Golden Ear, so I made them all general"

The only new bit of dynamic information needed for the email is the [#LeaveNoTrace](https://www.youtube.com/watch?v=zcktbVamiQg&t=1s) link. But I cannot find a similar video for Golden Ears. If we are going to be sending the same video link for each park this ticket is ready for QA review. If there is more video links I will need a list of all them all to re-assess how to go about this.  Until that is decided I will move this ticket to blocked.

**Comment by Dianadec** [comment]
@meyerdarcie  flagging this blocker for you and possibly @ndelraye  from @Christopher-walsh22 :

> 
> The only new bit of dynamic information needed for the email is the [#LeaveNoTrace](https://www.youtube.com/watch?v=zcktbVamiQg&t=1s) link. But I cannot find a similar video for Golden Ears. If we are going to be sending the same video link for each park this ticket is ready for QA review. If there is more video links I will need a list of all them all to re-assess how to go about this. Until that is decided I will move this ticket to blocked.

**Comment by meyerdarcie** [comment]
@ndelraye see comment above re #leavenotrace link - are we sending the same video for each park?

**Comment by ndelraye** [comment]
Marshall made the vehicle email generic so it could be used for Golden ears as well as Garibaldi, but just realized the the leave no trace links are unique to each park. Marshall needs to decide what he would like to do, either remove this link, clarify the link is specific for Garibaldi or add in another one for Golden ears if there is one

**Comment by meyerdarcie** [comment]
@MarshallHenson - see comment above from Nicole - we're trying to work out a few last minute items for the Garibaldi emails. Are you ok with removing the leave no trace link?

**Comment by Christopher-walsh22** [comment]
Awesome! I have updated the template in TEST moving this to QA.

**Comment by manuji** [comment]
Tested on TEST: **Pending**

@Christopher-walsh22 few minor issue found. 

1. The first paragraph starts with a underscore (refer to the image attached)



![Image](https://github.com/user-attachments/assets/97b338d9-c109-46bc-b16f-6816730154ef)

**Comment by Christopher-walsh22** [comment]
@manuji That is strange. I have about 20 of these confirmation emails without that appearing. I will look into it, are you viewing the email in outlook? 



![Image](https://github.com/user-attachments/assets/1b5eaf34-c25c-44d7-a810-48f06360857d)

**Comment by Christopher-walsh22** [comment]
Outlook must have been removing that for me for some reason. 

I have fixed the template and made the first paragraph italicized like the sample text shows.  Moving back to QA.

**Comment by manuji** [comment]
Tested on TEST: passed
* This is good to go to PROD. 
* Passing to PO review. 

@Christopher-walsh22 , let me know when you update the PROD email template, if users spare me one pass to book, I will verify the email. :)

**Comment by Christopher-walsh22** [comment]
Updated the Prod template! hopefully you can get a pass!

**Comment by manuji** [comment]
@Christopher-walsh22 , I am sorry I failed to recognize one mistake. Could you please update both TEST and PROD template to reflect this line to match with the Figma and the Word doc:

**Issue:**


![Image](https://github.com/user-attachments/assets/cd0ae867-4287-4f99-be86-f2e9e347c74f)


Expected: Should read "Thank you. We hope you enjoy your visit!"



![Image](https://github.com/user-attachments/assets/79a58793-ad79-4c52-969e-11378f21cb69)

**Comment by Christopher-walsh22** [comment]
updated

**Comment by manuji** [comment]
Thank you so much! This change has been successfully done on PROD.

**Comment by meyerdarcie** [comment]
Moving to done.
