### ISSUE TITLE
[S] DUP: Remove SMS notifications for Golden Ears Alouette South Beach Day-Use Parking Lot

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-public#421]
#### Description:
We need to remove the SMS opt-in option for Golden Ears Alouette Lake South Beach Day-Use Parking Lot as it is causing us to hit the GC Notify SMS limit. If we remove this option, there will be less than 1,000 texts sent/day, even on busy weekends. 

Explanation to public will be added to the FAQ by Marshall.

![Image](https://github.com/user-attachments/assets/bd4e1e60-10d4-422c-bfb1-8c9314874ac9)

#### Acceptance Criteria:
[Note: Use 'Given/When/Then' format if it makes sense to. Otherwise, a simple checklist that can be tested.]

#### Development Checklist:

- [ ] remove check box and text field for phone number
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Question for refinement: Is it easy enough to remove these SMS notifications?

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this change request has been done and the page looks good. 
* Verified the change on Mobile device as well. 
* Passing to PO review. 

One issue related to the Golden Ears Park was found and would need to fix it before deploying to PROD.
https://github.com/bcgov/parks-reso-public/issues/442

**Comment by meyerdarcie** [comment]
Working as intended, moving to done. Will need to address UI issue in #442 before deploying to prod.
