### ISSUE TITLE
[M] DUP: Passes are bookable prior to 7:00am without a refresh

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-public#424]
**Describe the bug**
Currently, DUP are bookable if a user is on the site at 6:59 and when it rolls over to 7:00am the greyed out box becomes clickable. To prevent any possibility of skipping the line, and improve user experience, we need to force users to refresh if they are on the site before 7:00am, or bookable only after arriving after 7:00am. 

**To Reproduce**
1. Anytime before 7:00am, go to https://reserve.bcparks.ca/dayuse/registration
2. When it rolls over to 7:00am, proceed with booking a pass, without needing a refresh

**Expected behavior**
Users should be required to refresh prior to booking passes at 7am. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Developer approach could be to pull system time from the `/api/config` endpoint, and use that as the current tme instead of `new Date()` in the front-end in order to show/hide certain options in the UI.  Calculating calculating based on the user's tz or currently set time(and sometimes incorrect) puts the browser into modes that are not reflective of actual server-based timings.
- Prior to the user hitting next after selecting facility/date/type and immediately going to the turnstile, we may want an additional check on whether that is an allowable action before the front-end goes through the turnstile challenge.

**Comment by Dianadec** [comment]
Separate - public heads-up of future ideas to make it more fair

**Comment by Christopher-walsh22** [comment]
@MarshallHenson 

I had a quick call with @pavelcreates  today and he gave me a great starting point for a design when a user is trying to book a pass outside the allowed window. 

![Image](https://github.com/user-attachments/assets/f9c5f293-03f9-4ba1-b29c-59b0ac168d94)

Pavel had also suggested using the yellow warning box instead of the red in the image, but just so you have an idea of the path forward I figured I would share. Let me know if you would like any immediate changes or I can give you a demo once we have first pass implemented.

**Comment by MarshallHenson** [comment]
This is great. Agree w/ yellow. Demo would be appreciated. Reminder to prompt people to refresh!

**Comment by Christopher-walsh22** [comment]
@MarshallHenson 

Here is a quick iteration which lead to some more conversations with Pavel.

![Image](https://github.com/user-attachments/assets/b813fafe-c7df-49b4-b852-927fe7c71808)


As we were discussing this version. I brought up the potential problem of a user opening this page prior to 7am, but not selecting a booking date or facility until after 7am. The user would not receive the warning telling them to refresh until after the selection is made. Pavel has suggested removing the date select functionality when loading outside the allowed booking window. Leaving just the back button and the warning. I am going to switch things around to match that work flow but figured I give you an idea of the wording and color that I currently have.

**Comment by Christopher-walsh22** [comment]
Here is what the page will load as if it is outside the booking now. Marshall I will try to schedule a call tomorrow to do a quick demo and see if we can come up with any other issues a user could come across with this process. 

![Image](https://github.com/user-attachments/assets/9c1f7b33-12ec-45b5-a085-f54c95e21129)

**Comment by MarshallHenson** [comment]
Thanks for the screenshots @Christopher-walsh22. The most recent screenshot does not show their date or facility selection - I think we want those to remain.

**Comment by Christopher-walsh22** [comment]
@MarshallHenson  I have changed it back to the previous version where you can see the booking window, and facility selection. Let me know if you want a demo from my local machine.

**Comment by manuji** [comment]
Tested on TEST: **Failed**
* When a park is set to Booking Days Ahead: 3 days and Booking Opening Time: 5PM, I cannot book a pass for the current date or the next 2 days. The logic should only apply for passes beyond the booking days ahead number. Refer to Garibaldi, Cheakamus facility on TEST environment. Please let me know if I have misunderstood the logic. 

FYI @Christopher-walsh22

**Comment by Christopher-walsh22** [comment]
@manuji I believe your right. I just got off a call talking through this with @cameronpettit and he was able to break down the reasoning/logic clearer for me. I went the wrong way implementing this. Ill switch back over to it and post a comment when a new iteration is in DEV.

**Comment by Christopher-walsh22** [comment]
@MarshallHenson @manuji @pavelcreates 

I just had another call figuring out what needs to be done for this ticket. As it is written, I had implemented a feature to make no passes available prior to 7am. What is actually required is that passes are not able to be booked more than 48hrs prior to the pass's facility opening hour. You will need to refresh you page if it was opened more than 48hrs in advance. AM/PM/ALL-DAY pass will effect this. Passes for the current day and next day will still be available for booking at this time.  This ticket will only effect the handling of passes at the furthest out booking day when the date is available but the current time is not past the facility is not opening hour (AM/PM). 

If I am missing any parts of this please let me know and we can arrange a call.

**Comment by Christopher-walsh22** [comment]
@manufacturing @pavelcreates 

After doing a demo for @MarshallHenson  on Thursday October 17th it was decided the best implementation was to not use warning alert and instead add the information regarding the required refresh to the "Important Booking Information" section.  I will move this ticket to blocked until the approved wording is available for that. Once that we have that I will be able to update this tickets acceptance criteria. 

It was also determined all passes would become available at 7am so the differentiating between AM and PM to apply the warning would not be required in the facility selection process. The system time supplied from API will still be used on page load to determine if the booking window is open or closed.

**Comment by manuji** [comment]
Hi @Christopher-walsh22 where can I find the copy that was approved to be added to the "Important Booking Information" ?

**Comment by manuji** [comment]
Tested on TEST: Pending
* When booking a pass for a facility which has the booking window is only on the same day, if the user tries to book before the booking window is open, it shows the error given below; which doesn't explain the actual situation. 
![Image](https://github.com/user-attachments/assets/421207d5-77d5-4e94-9234-701a5fd64950)
* Verified for the other booking window options, the date is disabled until the booking window is open. 

@Christopher-walsh22, I also would like to know where to find the approved copy updates.

**Comment by Christopher-walsh22** [comment]
Sorry I never posted the screen shot from my conversation with @MarshallHenson 

This was the wording from our last conversation:

![Image](https://github.com/user-attachments/assets/9dbf9fd7-fa68-4344-b762-20420914aad1)

**Comment by manuji** [comment]
@LindsayMacfarlane & @Dianadec what do you think about the issue I have reported in my previous comment?

**Comment by Dianadec** [comment]
@Christopher-walsh22 do you know if this message can be customized depending on the error? or is it only one error message? cc @cameronpettit 

![Image](https://github.com/user-attachments/assets/454e2c8e-7d2c-46d4-960b-82354d07a64d)

**Comment by Christopher-walsh22** [comment]
@Dianadec  This can be changed, I can jump onto finding a fix for it this afternoon. 

I did reply to this in the teams chat about it. I believe this would be the same situation that has always happened on Sunday morning (only 1 available booking day, prior to opening time).  

Ill dig into finding the exact error and make a toast message for it if someone can lock down the wording the wording we want to use.

**Comment by Dianadec** [comment]
@MarshallHenson if we want to customize this toast message error, would the wording be similar to:
"It is not currently within the booking window." ? cc @LindsayMacfarlane

**Comment by manuji** [comment]
Setting the passes to be booked on the same is contradictory to the Booking information copy. Just for your information;
![Image](https://github.com/user-attachments/assets/ffa7069a-3ce8-4ca3-8d09-80fd9abab24d)

**Comment by manuji** [comment]
Tested on TEST: 

* 

Observations:
* If Booking opening time is set to a time in the PM, then booking AM passes create issues reported here -> https://github.com/bcgov/parks-reso-public/issues/471
* For a specific park, all the facilities should be set up in the same settings (booking ahead days and Booking opening time) to avoid errors.
* Booking ahead days set to same day shows incorrect error messages reported here -> https://github.com/bcgov/parks-reso-public/issues/476
*

**Comment by LindsayMacfarlane** [comment]
Thank you @Christopher-walsh22 and @manuji - approving. 

FYI @MarshallHenson
