### ISSUE TITLE
DUP Spelling error in message "New - text message reminders with cancellation links..."

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#425]
#### Description:

Received spelled incorrectly:

![Image](https://github.com/user-attachments/assets/21d2a1f1-34a1-4624-8bb6-9f9ee6882b98)

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
I would like to work on this issue.

Thanks and Regards,
Mohit Kambli
