### ISSUE TITLE
Designs: Land acknowledgement for DUP

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-public#428]
#### Description:

This ticket is to create designs for adding a land acknowledgement to DUP, that will be consistent across bcparks.ca, and camping.bcparks.ca

Desktop design for camping.bcparks.ca:
![Image](https://github.com/user-attachments/assets/b9ef0108-6bb1-4b15-990e-a7051afd0474)

Mobile design for camping.bcparks.ca:
![Image](https://github.com/user-attachments/assets/84eed9fa-88a5-42ba-9d34-682be1136a3e)

#### Acceptance Criteria:

- [ ] The acknowledgement reads: "We acknowledge all First Nations on whose claimed territories BC Parks were established. We honour their connection to the land and respect the importance of their diverse teachings, traditions, and practices within these territories.”
- [ ] designs for land acknowledgement are in figma and linked here

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
Sprint Planning notes: Could be a good place for @pavelcreates  to start, with support from @meredithom

**Comment by meyerdarcie** [comment]
If there is capacity to pick this design ticket up before end of week I would be very grateful! Reservation Services is working on a decision note for exec and would like include designs in the note (@ndelraye @meredithom @pavelcreates)

**Comment by ndelraye** [comment]
sure, seems simple enough

**Comment by Dianadec** [comment]
Reference: CMS ticket: https://bcparksdigital.atlassian.net/browse/CMS-256?focusedCommentId=23251

**Comment by meyerdarcie** [comment]
@ndelraye - Reservation services indicated that they no longer require these designs and will let us know next steps after DM approval. Thanks for picking this up.
