### ISSUE TITLE
[L] DUP SAM front end deployment (admin/public)

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-public#438]
#### Description:

Goal is to be able to deploy DUP via SAM without the use of any terraform.

**Acceptance criteria**
- [ ] Everything that is AWS side will need to be setup using SAM:
  - [ ] Cloudformation
  - [ ] Cloudwatch
  - [ ] S3
- [ ] All tests pass
- [ ] GitHub Actions deploys successfully to dev, test, prod
- [ ] Terraform is completely removed
- [ ] Old, non-SAM code is removed
- [ ] Full smoke test to make sure everything ported over properly

#### Development Checklist:

- [ ] All tests are converted to work with the SAM changes, this mean path changes and conversion(s) for layers
- [ ] All tests run successfully and pass
- [ ] Update READMEs accordingly

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the new deployments are using SAM and no errors were encountered when deploying to the test environment.
* Verified that the new vanity urls to the DUP Admin and Public sites are working without any errors. 
* Passing to PO review.

**Comment by LindsayMacfarlane** [comment]
Hi Everyone - thanks for all your work on this one! As I'm still learning our processes and apps - can someone let me know what I can specifically test in relation to this ticket? I've taken a look at all of our test environments for public/admin and (based on current knowledge) things look good! 

cc @davidclaveau @Christopher-walsh22 @manuji @Dianadec
