### ISSUE TITLE
DUP: re-order parks on DUP home page [S]

### ISSUE THREAD

**Issue by MarshallHenson** [bcgov/parks-reso-public#449]
#### Description:

This ticket is to change the order priority of DUP parks to: 
- passes required (alphabetical)
- special closure (alphabetical) 
- passes not required (alphabetical) 

#### Acceptance Criteria:
Given that I am a visitor to the DUP reservation site 
When I attempt to select a park 
Then I see the parks that require a pass first, followed by parks with special closures, followed by parks that do not require a pass currently 

#### Development Checklist:

- [ ] Parks are grouped by open/closed status

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

![Image](https://github.com/user-attachments/assets/f6048075-41a4-4e67-8c5b-0c5aa946ab6b)

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [x] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [x] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by manuji** [comment]
Tested on TEST: Pending
* Tested and noticed that the display order of parks when set to Special closure notice is incorrect. 
![Image](https://github.com/user-attachments/assets/c318590e-91eb-4018-9ebb-71eb6348fb9d)
 FYI @Christopher-walsh22 

Expected order:

- [ ] If all parks have the same status (eg: All set to either "Passes required", "Closed" or "Special closure notice")  -> Should be in alphabetical order. 
- [ ] If the parks with different statuses then, first sort by status in the order of "passes required", "special closure" and "passes not required" and among the parks with same status sort them in Alphabetical order.

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the display order is correct when all parks in the same status
* Verified that the display order is correct when parks have different status
* Passing to PO review.

**Comment by LindsayMacfarlane** [comment]
Tested on TEST: **Passed**

- Updated Park status in Admin for several parks and then confirmed that those parks display status and order was updated accordingly on frontend.

Closing ticket as complete. Thanks for all your work @Christopher-walsh22 !
