### ISSUE TITLE
DUP: Issues with Rubble Creek facility specific message [S]

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-reso-public#450]
Scenario:
* Navigate to the DUP on TEST environment: https://reserve.bcparks.ca/dayuse/
* Book a pass in Garibaldi, Rubble Creek sub area. 
* Check the Facility specific messaging on the confirmation page. 

Issues:
1. The 3rd safety information point should show "A" in lower case in the sentence "Create A [trip plan](https://www.adventuresmart.ca/trip-plan-app/)."
2. The word "summitting" should be spelled as "summiting" in sentence "BC Parks strongly advises against summitting Black Tusk."

![Image](https://github.com/user-attachments/assets/a12aa21a-a9c9-4876-825e-e12ad8e5f33d)

#### Acceptance Criteria:

- [ ] Text across all facilities has a lower case "a" in "Create a [trip plan](https://www.adventuresmart.ca/trip-plan-app/)."
- [ ] The spelling of summiting is corrected

**Comment by Christopher-walsh22** [comment]
As discussed in refinement, I checked to see if these typos were on any of the other facility specific confirmation pages and I did not see them anywhere else.

**Comment by manuji** [comment]
Tested on [TEST](https://test-dup.bcparks.ca/dayuse/): **passed**
* verified that this issue has been fixed.
