### ISSUE TITLE
DUP - UI replace water droplet icon with water glass icon

### ISSUE THREAD

**Issue by janemoxd** [bcgov/parks-reso-public#459]
The Font Awesome 'droplet' icon is currently being used for drinking water messaging on DUP.
Need to remove that icon and use the 'glass-water' icon instead.

**The icon is:**
glass-water regular 24px wide x 32px high

**Notes**
The content team reviewed all the icons being used and decided on the glass icon to better represent drinking water. So this ticket will bring DUP into line with the icons being used on BC Parks.

See the [icons table in the Figma in-use library](https://www.figma.com/design/UzktKvkQuIPqxbUgTnljQt/BCParks.ca---In-Use-Library?node-id=2599-1364&t=OZVDPThFj9yGWznQ-1) for further info.

**Comment by LindsayMacfarlane** [comment]
Pulling this in as a potential Sprint 21 or 'need more work' during sprint 20. Assuming low effort and quick fix if someone needs a ticket.

**Comment by manuji** [comment]
Tested on TEST: Pending
* Verified that the icon has been changed on the Garibaldi park - Diamond Head facility specific message. 

Issue:
* haven't updated on the facility specific message for Garibaldi - Rubble creek 

Assigning back to @Christopher-walsh22 .

**Comment by LindsayMacfarlane** [comment]
Tested on Test:

- Garibaldi, Diamond Head (am) - passed

I did find this icon...but I may have been on the old test site and can't remember what park I was in. (bad tester - apologies!)

![Image](https://github.com/user-attachments/assets/7b99886d-deee-4d39-ac61-a42b732d4219)

Approving. 

Thank you @Christopher-walsh22 and @manuji

**Comment by manuji** [comment]
It could be cache too. Happened to me as well. After clearing cache icon got updated. Thank you for approving @LindsayMacfarlane
