### ISSUE TITLE
DUP: Q3 Feature Prioritization

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#466]
#### Description:

Similar to how we met with A&R team, this ticket is to work with the program area to help determine priorities for DUP in the upcoming months.

#### Acceptance Criteria:
- [x] Schedule a 1-hour session with Marshall and dev reps
- [x] Create mural template and include current DUP backlog tickets
- [x] bring forward recent notes about priorities (LM and MH)
- [x] Hold session
- [x] Post follow-up of session

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**
- https://app.mural.co/t/bcparks2575/m/bcparks2575/1729124366479/8adea59d9e76fb3eb1e33395f1c1857a8c07fb7b?sender=u45121c4ffd92ebc876901869 

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by LindsayMacfarlane** [comment]
Mural board: https://app.mural.co/t/bcparks2575/m/bcparks2575/1729124366479/8adea59d9e76fb3eb1e33395f1c1857a8c07fb7b?sender=u45121c4ffd92ebc876901869 

cc @Dianadec

**Comment by LindsayMacfarlane** [comment]
@MarshallHenson - here's the ticket with applicable links for our prioritization session next week :)

**Comment by LindsayMacfarlane** [comment]
Closing this ticket. @Dianadec let me know if there is anything I missed :)

- follow up provided to Niamh for awareness
- post made in general channel summarizing discussion https://teams.microsoft.com/l/message/19:7gg3pxzoL-hjZRHvr5ggkjxP9O8cah6SWqiYiz2CD_M1@thread.tacv2/1732224216894?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=aadf267c-d6ab-4c8c-9cff-e574713575e6&parentMessageId=1732209304620&teamName=External%3A%20Team%20Osprey&channelName=General&createdTime=1732224216894
