### ISSUE TITLE
Design: Mt. Seymour confirmation page messaging update

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#467]
#### Description:

For the winter 2024/2025 season, Mount Seymour will need to have its facility-specific confirmation page messaging updated. Needed by the start of the season which is December 10th, 2024. Dec. 12 is the date of enforcement so that 10th would be the date that people can book passes.

As a Mount Seymour visitor, I want to get park specific information so that I can be better prepared.

#### Acceptance Criteria:
- Wireframes created according to messaging word document: https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7B1903155C-4272-44B9-9222-37186C1FA116%7D&file=Mount%20Seymour%20Confirmation%20Page.docx&action=default&mobileredirect=true
- wireframes created in figma in the same place as the previous confirmation messaging designs if that makes sense: https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=4759-10586&t=8tjt3J4fqzO79fBU-0
- Icons are consistent with previous messaging updates (eg: Joffre lakes)
- wireframes added to implementation ticket

#### Development Checklist:

- [ ] Reference previous designs for which icons to use - connect with NDR if questions: https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=4759-10586&t=8tjt3J4fqzO79fBU-0
- [ ] - [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking https://github.com/bcgov/parks-reso-public/issues/468

**Relevant documentation as reference**
Previous update tickets: https://github.com/bcgov/parks-reso-public/issues/407

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
@MarshallHenson could you let us know once the content has been approved? We can't pull this ticket in until it is. Thanks! cc @LindsayMacfarlane

**Comment by MarshallHenson** [comment]
should be good to go!

**Comment by Dianadec** [comment]
@meredithom I added a direct link to the previous figma areas used for the other facility messaging to help with icons etc: https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=4759-10586&t=8tjt3J4fqzO79fBU-0

cc @LindsayMacfarlane

**Comment by Dianadec** [comment]
Goal to complete this design by Friday, November 22nd, 2024 so that we have time to implement it by December 10th.

**Comment by LindsayMacfarlane** [comment]
@meredithom - confirming we can pull this ticket into in-progress? I believe you mentioned at stand-up that you started looking at the design.

**Comment by meredithom** [comment]
@MarshallHenson added some changes to the word doc based on how things were looking in practice. Less is more when it comes to the important information. I also tweaked the wildlife line to match the other sub-areas.

edited text with context: 
![Image](https://github.com/user-attachments/assets/20278ab9-9fb3-43c9-a72b-0399a65451b6)

**Comment by MarshallHenson** [comment]
approved the changes in the word doc - all looks good :)

**Comment by meredithom** [comment]
Designs:
https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=6414-13202&t=WzO8xHBZtEXJ8c3V-1

Will be added to dev ticket.
