### ISSUE TITLE
Implementation: Mt. Seymour confirmation page messaging update [Due in PROD by Dec 10]

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#468]
#### Description:

For the winter 2024/2025 season, Mount Seymour will need to have its **facility-specific confirmation page** messaging updated. Needed by the start of the season which is December 10th, 2024. Dec. 12 is the date of enforcement so that 10th would be the date that people can book passes.

As a Mount Seymour visitor, I want to get park specific information so that I can be better prepared.

#### Acceptance Criteria:
- [ ] By December 10th, the facility-specific confirmation page messaging is updated according to the wireframe below.

#### Development Checklist:

- [ ] UI matches [designs](https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=6414-13202&t=WzO8xHBZtEXJ8c3V-1) (See notes for screenshots)
- [ ] ...

#### Dependencies

- Blocked by https://github.com/bcgov/parks-reso-public/issues/467
- Blocking

**Relevant documentation as reference**
Previous update tickets: https://github.com/bcgov/parks-reso-public/issues/345

**Definition of Ready**

- [x] Acceptance criteria are included
- [x] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- The parking symbols on all facilities should be updated to the [square version](https://fontawesome.com/icons/square-parking?f=classic&s=regular) to match what is used on bcparks.ca 
-

**Comment by meredithom** [comment]
![Image](https://github.com/user-attachments/assets/bbe49ead-4076-4c72-90d4-a024b63b6dca)
![Image](https://github.com/user-attachments/assets/995839e6-178d-46ea-a344-f79f482a48a3)

**Comment by Dianadec** [comment]
@LindsayMacfarlane  once you've PO Reviewed the design ticket, we can pull this implementation ticket in.

**Comment by MarshallHenson** [comment]
good question @Dianadec - currently, we only have the emails broken down into vehicle & trail (Joffre). As of now, Mount Seymour will continue to receive the basic vehicle confirmation email with some generally applicable responsible rec messaging. We could, however, make a new template for just Seymour. We decided against this for the summer as it would have meant building out 6 new templates for the 8 facilities.

**Comment by manuji** [comment]
Tested on TEST: **Pending**
* Issue with the link to check "[today's conditions at Mt Seymour](https://myseymour.ca/the-mountain/todays-conditions-hours).". Incorrect link takes me to a dead page. The correct link should be: https://mtseymour.ca/the-mountain/todays-conditions-hours
* The Visitor guideline about parking is missing the closing bracket after the link to parking map. 
* In Visitor guideline abut dogs in leash, the implemented copy reads "Pets" instead of "Dogs"

![Image](https://github.com/user-attachments/assets/80ab495e-4c57-4515-b886-304440f7a185)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed. 
* Passing to PO review. @LindsayMacfarlane

**Comment by LindsayMacfarlane** [comment]
Looks great! Thank you @Christopher-walsh22 ! Tested on test. Passed and approved :)

Thanks for your testing (and attention to detail) @manuji !
