### ISSUE TITLE
Updates for end of Daylight savings

### ISSUE THREAD

**Issue by Christopher-walsh22** [bcgov/parks-reso-public#472]
#### Description:
Daylight savings time has ended, we need to change the DUP front end to use noon as the PM start time instead of 1pm

#### Acceptance Criteria:
When a user is booking a pass they will see 12 as the default time for a pm pass starting

#### Development Checklist:

- [ ] AM passes expire at 12
- [ ] PM passes start at 12

#### Notes:
- Due to work done earlier in the year this should only require updating the PM opening time constant
- This is very similar to work done last year for [Ticket280](https://github.com/bcgov/parks-reso-public/pull/287)

**Comment by manuji** [comment]
Tested on TEST environment: **Passed**
* verified that the copy has been updated. 
* Passing to PO review. 
![Image](https://github.com/user-attachments/assets/dabd0036-54e4-4c24-bdb8-67ffdff1d6ce)

**Comment by LindsayMacfarlane** [comment]
Thank you @Christopher-walsh22 and @manuji - approved.

FYI @MarshallHenson
