### ISSUE TITLE
Remove "Information" from heading 'Safety Information' on each facility page

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#474]
#### Description:

Each Facility page in DUP currently has a heading that says "Safety Information". We need to remove 'information' so that the heading just says "Safety"
https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=4759-10586
![Image](https://github.com/user-attachments/assets/f7423ff1-f13a-4cae-99e3-9da563c283ff)

#### Acceptance Criteria:
- [x] Remove 'information' from Garibaldi facility page
- [ ] Remove 'information' from Golden Ears facility page
- [x] Remove 'information' from Joffre Lakes facility page
- [ ] Update figma designs accordingly (remove the word from each design)

#### Development Checklist:

- [ ] 
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment]
@MarshallHenson please review this ticket description and add anything as needed. Thanks!
cc @LindsayMacfarlane

**Comment by Christopher-walsh22** [comment]
Just wanted to make a quick note on this ticket. We have not done the facility specific messaging for Golden Ears, so there is no "Safety Information" to edit for those facilities. We had created tickets for that work in the summer but it was put off and deemed not urgent at the time. I will update those figmas accordingly.

**Comment by Dianadec** [comment]
Good catch! thanks Chris

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that Joffre lakes has been updated
* Verified that Garibaldi - Rubble creek has been updated
* Verified that Garibaldi - Cheakamus has been updated
* Verified that Garibaldi - Diamondhead has been updated
* Passing to PO review. 

Note: The figma hasn't been updated yet as per the AC.

**Comment by LindsayMacfarlane** [comment]
Thank you @Christopher-walsh22 for your work on this and for your testing @manuji ! As always, appreciate all your work!

Tested on test: Passed. 

- Garibaldi - Diamond head

(note: tested less than Manuji)

Approved.
