### ISSUE TITLE
DUP Firewall fix

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#490]
#### Description:

When the firewall is turned on in PROD, it blocks users from accessing the public side (prob admin as well).
A setting changed - from the SAM build - in the firewall or elsewhere. So this ticket is to troubleshoot a bit and resolve this issue.

#### Acceptance Criteria:

- [ ] able to book a pass through the front-end with the firewall turned on

#### Development Checklist:

- [ ] Troubleshoot firewall settings as per description above.
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Christopher-walsh22** [comment]
All of the firewall settings have been re-activated in PROD. We have mirrored the setting that were causing the issues to be in TEST. You are now able to book passes in both environments now. 

Testing this should only require accessing the homepage and not seeing the "LOCAL ENVIRONMENT" banner.

**Comment by manuji** [comment]
Tested on PROD: **Passed**
* Verified that this issue has been fixed. 
* Moving to Done. 

FYI @LindsayMacfarlane
